SET(TEFRI_TESTS_SOURCES
    TestPipeline.h
    TestRingQueue.h
    TestTakeLast.h
    TestFilter.h
    TestObjectHolder.h
    TestCarryOperator.h
    TestPipelineBuilder.h
    TestTefri.h
    main.cpp
)
